[package]
name = "avr-serial"
version = "0.1.0"
edition = "2021"

[dependencies]

[features]
hardware-atmega328p = []

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
lto = true
codegen-units = 1
panic = "abort"

